"""
MedScan AI — Multi-Disease Risk Predictor
Flask Backend
Run: python app.py   →  http://127.0.0.1:5000
"""

import matplotlib
matplotlib.use('Agg')          # must come before pyplot import

from flask import Flask, request, render_template, send_from_directory, jsonify
import joblib, pandas as pd, numpy as np, shap, json
import matplotlib.pyplot as plt, matplotlib.ticker as ticker
import io, base64, os, copy, warnings

warnings.filterwarnings('ignore')

app = Flask(__name__)

# ── Absolute paths so the app works from any working directory ────────────────
BASE_DIR   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(BASE_DIR, 'saved_models')

# ── Load everything at startup (once) ────────────────────────────────────────
print("[MedScan] Loading models...")
models = {
    'Diabetes':      joblib.load(os.path.join(MODELS_DIR, 'Diabetes_model.joblib')),
    'Heart Disease': joblib.load(os.path.join(MODELS_DIR, 'Heart_Disease_model.joblib')),
    'Liver Disease': joblib.load(os.path.join(MODELS_DIR, 'Liver_Disease_model.joblib')),
}
background_data = joblib.load(os.path.join(MODELS_DIR, 'background_data.joblib'))

# Use a small subset of background samples → fast SHAP (PermutationExplainer)
bg_small = {name: shap.sample(bg, 25) for name, bg in background_data.items()}

# ── Load pre-computed validation metrics (generated by test_holdout_evaluation.py) ──
# JSON uses underscore keys (e.g. 'Heart_Disease'); map to space keys used in models dict.
_METRICS_PATH = os.path.join(MODELS_DIR, 'validation_metrics.json')
with open(_METRICS_PATH) as _f:
    VALIDATION_METRICS = json.load(_f)

print("[MedScan] Ready.")

# ── Feature configuration ─────────────────────────────────────────────────────
MODEL_FEATURES = {
    'Diabetes':      ['RIDAGEYR', 'LBDGLUSI', 'LBXGLU', 'BMXWAIST', 'BMXBMI', 'BPXSY1', 'URDACT'],
    'Heart Disease': ['RIDAGEYR', 'URDACT', 'BMXWAIST', 'RIAGENDR', 'LBXTC'],
    'Liver Disease': ['RIDAGEYR', 'LBXGLU', 'LBDGLUSI', 'BPXSY1', 'URXUMA',
                      'LBXSATSI', 'LBXSASSI', 'LBXSGTSI', 'LBXSAPSI', 'LBXSTB', 'LBXSAL'],
}

# ── Thresholds loaded from validation_metrics.json (clinically optimised) ────
# JSON keys use underscores; app uses space-separated names — build a mapping.
_KEY_MAP = {'Diabetes': 'Diabetes', 'Heart Disease': 'Heart_Disease', 'Liver Disease': 'Liver_Disease'}
THRESHOLDS = {
    disease: VALIDATION_METRICS[json_key]['threshold']['value']
    for disease, json_key in _KEY_MAP.items()
}

# Human-readable labels for SHAP plots
SHORT_LABELS = {
    'RIDAGEYR':  'Age',
    'RIAGENDR':  'Gender',
    'LBXGLU':   'Glucose (mg/dL)',
    'LBDGLUSI': 'Glucose (mmol/L)',
    'BMXBMI':   'BMI',
    'BMXWAIST': 'Waist (cm)',
    'BPXSY1':   'Systolic BP',
    'URDACT':   'ACR (mg/g)',
    'LBXTC':    'Cholesterol',
    'URXUMA':   'Urine Albumin',
    'LBXSATSI': 'ALT',
    'LBXSASSI': 'AST',
    'LBXSGTSI': 'GGT',
    'LBXSAPSI': 'ALP',
    'LBXSTB':   'Bilirubin',
    'LBXSAL':   'Serum Albumin',
}

FULL_LABELS = {
    'RIDAGEYR':  'Age (years)',
    'RIAGENDR':  'Gender',
    'LBXGLU':   'Blood Glucose (mg/dL)',
    'LBDGLUSI': 'Blood Glucose (mmol/L)',
    'BMXBMI':   'BMI (kg/m²)',
    'BMXWAIST': 'Waist Circumference (cm)',
    'BPXSY1':   'Systolic Blood Pressure (mmHg)',
    'URDACT':   'Albumin-Creatinine Ratio (mg/g)',
    'LBXTC':    'Total Cholesterol (mg/dL)',
    'URXUMA':   'Urine Albumin (µg/mL)',
    'LBXSATSI': 'ALT — Alanine Aminotransferase (U/L)',
    'LBXSASSI': 'AST — Aspartate Aminotransferase (U/L)',
    'LBXSGTSI': 'GGT — Gamma-Glutamyl Transferase (U/L)',
    'LBXSAPSI': 'ALP — Alkaline Phosphatase (U/L)',
    'LBXSTB':   'Total Bilirubin (mg/dL)',
    'LBXSAL':   'Serum Albumin (g/dL)',
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def risk_classify(prob, thresh):
    """Return (css_level, label, hex_color) for a probability."""
    if prob < thresh * 0.40:
        return 'low',      'Low Risk',       '#10b981'
    elif prob < thresh:
        return 'moderate', 'Moderate Risk',  '#f59e0b'
    elif prob < thresh * 2.0:
        return 'high',     'High Risk',      '#ef4444'
    else:
        return 'critical', 'Critical Risk',  '#dc2626'


def compute_shap_and_plot(model, bg, df, feats):
    """
    Returns (base64_png, pos_factors, neg_factors)
    where pos/neg_factors are lists of (label, shap_val, bar_pct).
    """
    predict_fn = lambda x, m=model: m.predict_proba(x)[:, 1]
    explainer  = shap.Explainer(predict_fn, bg)
    sv         = explainer(df)

    # Rename feature labels for the waterfall plot
    sv_renamed = shap.Explanation(
        values        = sv.values,
        base_values   = sv.base_values,
        data          = sv.data,
        feature_names = [SHORT_LABELS.get(f, f) for f in feats],
    )

    # ── Waterfall plot ────────────────────────────────────────────────────────
    plt.style.use('dark_background')
    shap.plots.waterfall(sv_renamed[0], show=False, max_display=10)
    fig = plt.gcf()
    fig.patch.set_facecolor('#0d1b2e')
    for ax in fig.get_axes():
        ax.set_facecolor('#0d1b2e')
        ax.tick_params(colors='#94a3b8', labelsize=8)
        ax.spines['bottom'].set_color('#1e3a5f')
        ax.spines['left'].set_color('#1e3a5f')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
    plt.tight_layout(pad=1.2)
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=140, bbox_inches='tight',
                facecolor='#0d1b2e', edgecolor='none')
    buf.seek(0)
    b64 = base64.b64encode(buf.getvalue()).decode()
    plt.close('all')

    # ── Top factors ───────────────────────────────────────────────────────────
    raw_vals = sv.values[0]                               # shape (n_features,)
    pairs    = [(FULL_LABELS.get(f, f), float(v)) for f, v in zip(feats, raw_vals)]

    pos_raw  = sorted([(n, v) for n, v in pairs if v > 0], key=lambda x: -x[1])[:3]
    neg_raw  = sorted([(n, v) for n, v in pairs if v < 0], key=lambda x: x[1])[:3]

    max_pos  = pos_raw[0][1] if pos_raw else 1.0
    max_neg  = abs(neg_raw[0][1]) if neg_raw else 1.0

    pos = [(n, v, min(int(v / max_pos * 100), 100))         for n, v in pos_raw]
    neg = [(n, v, min(int(abs(v) / max_neg * 100), 100))    for n, v in neg_raw]

    return b64, pos, neg
FIELD_RANGES = {
    'age':              (18, 85),
    'fasting_glucose':  (50, 500),
    'waist_cm':         (50, 200),
    'bmi':              (10, 70),
    'systolic_bp':      (70, 220),
    'acr':              (0, 5000),
    'sex':              (1, 2),
    'total_cholesterol':(50, 500),
    'urine_albumin':    (0, 500),
    'alt':              (0, 500),
    'ast':              (0, 500),
    'ggt':              (0, 500),
    'alp':              (0, 500),
    'total_bilirubin':  (0, 30),
    'serum_albumin':    (1, 6)
}

REQUIRED_FIELDS = list(FIELD_RANGES.keys())

API_FIELD_MAP = {
    'RIDAGEYR': 'age',
    'RIAGENDR': 'sex',
    'LBXGLU': 'fasting_glucose',
    'LBDGLUSI': 'fasting_glucose',
    'BMXBMI': 'bmi',
    'BMXWAIST': 'waist_cm',
    'BPXSY1': 'systolic_bp',
    'URDACT': 'acr',
    'LBXTC': 'total_cholesterol',
    'URXUMA': 'urine_albumin',
    'LBXSATSI': 'alt',
    'LBXSASSI': 'ast',
    'LBXSGTSI': 'ggt',
    'LBXSAPSI': 'alp',
    'LBXSTB': 'total_bilirubin',
    'LBXSAL': 'serum_albumin',
}

def build_feature_row(data, disease_space):
    feats = MODEL_FEATURES[disease_space]
    row = {}
    for col in feats:
        if col == 'LBDGLUSI':
            row[col] = float(data['fasting_glucose']) * 0.0555
        elif col == 'RIDAGEYR':
            row[col] = float(data['age'])
        elif col == 'RIAGENDR':
            row[col] = float(data['sex'])
        elif col == 'LBXGLU':
            row[col] = float(data['fasting_glucose'])
        elif col == 'BMXWAIST':
            row[col] = float(data['waist_cm'])
        elif col == 'BMXBMI':
            row[col] = float(data['bmi'])
        elif col == 'BPXSY1':
            row[col] = float(data['systolic_bp'])
        elif col == 'URDACT':
            row[col] = float(data['acr'])
        elif col == 'LBXTC':
            row[col] = float(data['total_cholesterol'])
        elif col == 'URXUMA':
            row[col] = float(data['urine_albumin'])
        elif col == 'LBXSATSI':
            row[col] = float(data['alt'])
        elif col == 'LBXSASSI':
            row[col] = float(data['ast'])
        elif col == 'LBXSGTSI':
            row[col] = float(data['ggt'])
        elif col == 'LBXSAPSI':
            row[col] = float(data['alp'])
        elif col == 'LBXSTB':
            row[col] = float(data['total_bilirubin'])
        elif col == 'LBXSAL':
            row[col] = float(data['serum_albumin'])
        else:
            row[col] = float(data.get(col, 0.0))
    return pd.DataFrame([row], columns=feats)

def get_shap_values(model, bg, df, feats, disease_space, top_n=3):
    try:
        predict_fn = lambda x: model.predict_proba(x)[:, 1]
        explainer = shap.Explainer(predict_fn, bg)
        sv = explainer(df)
        shap_vals = sv.values[0]
        
        api_shap = {}
        for col, val in zip(feats, shap_vals):
            api_field = API_FIELD_MAP.get(col, col)
            api_shap[api_field] = api_shap.get(api_field, 0.0) + float(val)
            
        results = []
        for field, val in api_shap.items():
            results.append({
                'feature': field,
                'shap_value': round(val, 4),
                'direction': 'increases_risk' if val > 0 else 'decreases_risk'
            })
            
        results.sort(key=lambda x: abs(x['shap_value']), reverse=True)
        return results[:top_n]
    except Exception as e:
        print(f"[SHAP Error] {e}")
        return []

@app.route('/api/predict', methods=['POST'])
def api_predict():
    try:
        try:
            data = request.get_json(force=True)
        except Exception:
            return jsonify({'error': 'Request body must be valid JSON', 'status': 400}), 400
        if data is None:
            return jsonify({'error': 'Request body must be valid JSON', 'status': 400}), 400

        # Validate all required fields present
        for field in REQUIRED_FIELDS:
            if field not in data:
                return jsonify({'error': f'Missing required field: {field}', 'status': 400}), 400

        # Validate ranges
        for field, (lo, hi) in FIELD_RANGES.items():
            val = data[field]
            try:
                val = float(val)
            except (ValueError, TypeError):
                return jsonify({
                    'error': f"Field '{field}' must be a number. Got: {val}",
                    'status': 422
                }), 422
            if not (lo <= val <= hi):
                val_str = str(int(val)) if val == int(val) else str(val)
                return jsonify({
                    'error': f"Field '{field}' out of valid range ({lo}–{hi}). Got: {val_str}",
                    'status': 422
                }), 422

        predictions = {}
        diseases_mapping = {
            'Diabetes': {'space': 'Diabetes', 'underscore': 'Diabetes'},
            'Heart_Disease': {'space': 'Heart Disease', 'underscore': 'Heart_Disease'},
            'Liver_Disease': {'space': 'Liver Disease', 'underscore': 'Liver_Disease'}
        }

        for disease_underscore, keys in diseases_mapping.items():
            space_key = keys['space']
            model = models[space_key]
            bg = bg_small[space_key]
            feats = MODEL_FEATURES[space_key]
            
            df = build_feature_row(data, space_key)
            prob = float(model.predict_proba(df)[:, 1][0])
            
            metrics_entry = VALIDATION_METRICS[disease_underscore]
            threshold = metrics_entry['threshold']['value']
            strategy = metrics_entry['threshold']['strategy']
            
            if prob >= threshold:
                label = 'High Risk'
            elif prob >= threshold * 0.6:
                label = 'Borderline'
            else:
                label = 'Low Risk'
                
            shap_top = get_shap_values(model, bg, df, feats, space_key)
            
            predictions[disease_underscore] = {
                'risk_probability': round(prob, 4),
                'risk_percent': round(prob * 100, 1),
                'risk_label': label,
                'threshold_used': round(threshold, 4),
                'threshold_strategy': strategy,
                'top_features': shap_top
            }

        return jsonify({
            'predictions': predictions,
            'metadata': {
                'model_version': '1.1.0',
                'validation_roc_auc': {
                    'Diabetes': VALIDATION_METRICS['Diabetes']['roc_auc'],
                    'Heart_Disease': VALIDATION_METRICS['Heart_Disease']['roc_auc'],
                    'Liver_Disease': VALIDATION_METRICS['Liver_Disease']['roc_auc']
                },
                'disclaimer': 'Educational prototype only. Not for clinical decision-making.',
                'api_version': '1.0'
            }
        }), 200

    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': 'Internal prediction error', 'status': 500}), 500


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route('/calibration/<disease>')
def calibration_image(disease):
    """Serve a pre-generated calibration curve PNG from static/calibration/."""
    static_calib_dir = os.path.join(os.path.dirname(__file__), 'static', 'calibration')
    if disease.endswith('_calibration.png'):
        filename = disease
    else:
        filename = f'{disease}_calibration.png'
    return send_from_directory(static_calib_dir, filename)


@app.route('/', methods=['GET', 'POST'])
def index():
    results   = None
    form_data = {}
    error     = None
    loaded_case_name = ''
    loaded_case_desc = ''

    if request.method == 'POST':
        loaded_case_name = request.form.get('loaded_case_name', '')
        loaded_case_desc = request.form.get('loaded_case_desc', '')
        try:
            g = float(request.form['glucose'])
            inputs = {
                'RIDAGEYR':  float(request.form['age']),
                'RIAGENDR':  float(request.form['gender']),
                'LBXGLU':   g,
                'LBDGLUSI': round(g * 0.0555, 4),
                'BMXBMI':   float(request.form['bmi']),
                'BMXWAIST': float(request.form['waist']),
                'BPXSY1':   float(request.form['sys_bp']),
                'URDACT':   float(request.form['acr']),
                'LBXTC':    float(request.form['cholesterol']),
                'URXUMA':   float(request.form['albumin']),
                'LBXSATSI': float(request.form['alt']),
                'LBXSASSI': float(request.form['ast']),
                'LBXSGTSI': float(request.form['ggt']),
                'LBXSAPSI': float(request.form['alp']),
                'LBXSTB':   float(request.form['bilirubin']),
                'LBXSAL':   float(request.form['serum_albumin']),
            }
            form_data = request.form.to_dict()
            results   = {}

            for disease, model in models.items():
                feats  = MODEL_FEATURES[disease]
                df     = pd.DataFrame([{k: inputs[k] for k in feats}], columns=feats)
                prob   = float(model.predict_proba(df)[0][1])
                thresh = THRESHOLDS[disease]
                lvl, lbl, color = risk_classify(prob, thresh)

                plot_b64, pos, neg = compute_shap_and_plot(
                    model, bg_small[disease], df, feats
                )

                # Gauge math: circumference for r=45 is 282.74
                circ   = 282.74
                offset = round(circ * (1 - prob), 2)

                results[disease] = dict(
                    prob     = prob,
                    prob_pct = f'{prob * 100:.1f}',
                    thresh   = thresh,
                    thresh_pct = int(thresh * 100),
                    level    = lvl,
                    label    = lbl,
                    color    = color,
                    circ     = circ,
                    offset   = offset,
                    plot     = plot_b64,
                    pos      = pos,   # [(label, shap_val, bar_pct), ...]
                    neg      = neg,
                )

        except Exception as exc:
            import traceback
            error = str(exc)
            traceback.print_exc()

    return render_template('index.html',
                           results=results,
                           form_data=form_data,
                           error=error,
                           loaded_case_name=loaded_case_name,
                           loaded_case_desc=loaded_case_desc,
                           metrics=VALIDATION_METRICS)



if __name__ == '__main__':
    # Default to port 5000 locally, but use the cloud provider's injected port (e.g. 7860 on HF)
    port = int(os.environ.get('PORT', 5000))
    # Bind to 0.0.0.0 so the app is accessible outside the container
    app.run(host='0.0.0.0', debug=True, use_reloader=False, port=port)
